'use client';
import { useEffect, useState } from 'react';

export default function AdminClient(){const [password,setPassword]=useState(''); const [data,setData]=useState(null); const [error,setError]=useState('');
async function load(){const res=await fetch('/api/admin/data',{cache:'no-store'}); const json=await res.json(); if(res.ok)setData(json); else setError(json.error||'Login required')}
useEffect(()=>{load()},[]);
async function login(e){e.preventDefault(); setError(''); const res=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}); const json=await res.json(); if(!res.ok){setError(json.error||'Login failed');return;} load();}
async function updateOrder(id,status){await fetch('/api/admin/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})}); load();}
async function updatePayment(id,status){await fetch('/api/admin/payments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})}); load();}
if(!data)return <main className="admin-shell"><form className="card form" onSubmit={login}><h1>VerifyMe Admin</h1><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin Password"/><button className="btn">Login</button>{error&&<p style={{color:'#f87171'}}>{error}</p>}<a href="/">Back Home</a></form></main>;
return <main className="admin-shell"><div className="panel"><h1>Admin Dashboard</h1><div className="grid"><div className="card"><h3>Total Orders</h3><h2>{data.orders.length}</h2></div><div className="card"><h3>Payments</h3><h2>{data.payments.length}</h2></div><div className="card"><h3>Services</h3><h2>{data.services.length}</h2></div></div><section className="section"><h2>Orders</h2><div className="card"><table><thead><tr><th>ID</th><th>Client</th><th>Service</th><th>Details</th><th>Status</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.client_name}<br/><small>{o.client_whatsapp}</small></td><td>{o.service_title}</td><td>{o.project_details}</td><td><select value={o.status} onChange={e=>updateOrder(o.id,e.target.value)}>{['PENDING','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div></section><section className="section"><h2>Payments</h2><div className="card"><table><thead><tr><th>ID</th><th>Order</th><th>Reference</th><th>Status</th></tr></thead><tbody>{data.payments.map(p=><tr key={p.id}><td>{p.id}</td><td>{p.order_id} — {p.client_name}</td><td>{p.reference_id}</td><td><select value={p.status} onChange={e=>updatePayment(p.id,e.target.value)}>{['PENDING','RECEIVED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div></section><a className="btn secondary" href="/">Back Home</a></div></main>}
